2g_lg_ecgs     = "lg_ecgs"

5g_lg_mecgw    = "lg_vsgw"
5g_lg_sa       = "lg_vsgw"
5g_lg_vmecgw   = "lg_vsgw"
5g_lg_vpgw     = "lg_vsgw"
5g_lg_vsgw     = "lg_vsgw"
5g_lg_vspgw    = "lg_vsgw"
5g_ss_cnf      = "ss_sa"
5g_ss_mecgw    = "ss_msc"
5g_ss_sa       = "ss_sa"
5g_ss_vmme     = "ss_vgw"
5g_ss_vspgw    = "ss_vgw"

cdma_tw_cglr   = "tw_vmss"

chg_nt_pcrf    = "nt_pcrf"
chg_nt_pg      = "nt_pcrf"

data_ng_sg     = "ng_sg"

hlr_tw_mrg     = "tw_vmss"
hlr_tw_ota     = "tw_vmss"
hlr_tw_wifiaaa = "tw_vmss"

ims_pi_ibc     = "pi_ibc"
ims_pi_vibc    = "pi_ibc"
ims_tw_db      = "tw_tiis"
ims_tw_icg     = "tw_vmss"
ims_tw_igw     = "tw_tiis"
ims_tw_slf     = "tw_vmss"
ims_tw_tgw     = "tw_tiis"
ims_tw_tiis    = "tw_tiis"
ims_tw_vgw     = "tw_vmss"
ims_tw_web     = "tw_tiis"

in_ua_ocs      = "ua_ocs"
in_ua_odb      = "ua_ocs"
in_ua_oms      = "ua_ocs"
in_ua_scp      = "ua_ocs"
in_ua_scpas    = "ua_ocs"
in_ua_sdp      = "ua_ocs"
in_ua_srg      = "ua_ocs"

iot_ct_lorag   = "ct_lora"
iot_ct_loras   = "ct_lora"
iot_nb_loras   = "nb_lora"
iot_ua_tp      = "ua_tp"

lte_ct_femto   = "ct_femto"
lte_lg_amme    = "lg_mme"
lte_lg_apgw    = "lg_mme"
lte_lg_asgw    = "lg_mme"
lte_lg_mme     = "lg_mme"
lte_lg_pgw     = "lg_mme"
lte_lg_sgw     = "lg_mme"
lte_lg_vpgw    = "lg_vsgw"
lte_lg_vsgw    = "lg_vsgw"
lte_lg_vspgw   = "lg_vsgw"
lte_pi_imgw    = "pi_imgw"
lte_ss_agw     = "ss_msc"
lte_ss_amme    = "ss_msc"
lte_ss_apgw    = "ss_msc"
lte_ss_asgw    = "ss_msc"
lte_ss_mbms    = "ss_msc"
lte_ss_mme     = "ss_msc"
lte_ss_mss     = "ss_msc"
lte_ss_pgw     = "ss_msc"
lte_ss_sgw     = "ss_msc"
lte_ss_vagw    = "ss_msc"
lte_ss_vgw     = "ss_vgw"
lte_ss_vmme    = "ss_vgw"
lte_ss_vmss    = "ss_msc"
lte_ss_vpgw    = "ss_msc"
lte_ss_vspgw   = "ss_vgw"
lte_tw_abc     = "tw_vmss"
lte_tw_auc     = "tw_vmss"
lte_tw_cmss    = "tw_cmss"
lte_tw_eir     = "tw_vmss"
lte_tw_grg     = "tw_vmss"
lte_tw_hlrdbs  = "tw_vmss"
lte_tw_hlrcs   = "tw_vmss"
lte_tw_hrg     = "tw_vmss"
lte_tw_hss     = "tw_vmss"
lte_tw_ibc     = "tw_vmss"
lte_tw_iglr    = "tw_vmss"
lte_tw_imgc    = "tw_imgc"
lte_tw_iwf     = "tw_vmss"
lte_tw_lglr    = "tw_vmss"
lte_tw_mss     = "tw_vmss"
lte_tw_npdf    = "tw_vmss"
lte_tw_npmf    = "tw_vmss"
lte_tw_npomp   = "tw_vmss"
lte_tw_tas     = "tw_vmss"
lte_tw_tasdbs  = "tw_vmss"
lte_tw_vibc    = "tw_vmss"
lte_tw_vmss    = "tw_vmss"
lte_tw_vtas    = "tw_vmss"

msg_hs_irelay  = "hs_mms"
msg_hs_trelay  = "hs_mms"
msg_hs_vmgapp  = "hs_mms"

sms_ua_smsc    = "ua_smsc"

wcdma_ct_femto = "ct_femto"
wcdma_lg_gmgw  = "lg_msc"
wcdma_lg_gmsc  = "lg_msc"
wcdma_lg_mgw   = "lg_msc"
wcdma_lg_msc   = "lg_msc"
wcdma_lg_sgsn  = "lg_msc"
wcdma_lg_urm   = "lg_urm"
wcdma_ss_aggsn = "ss_msc"
wcdma_ss_aurm  = "ss_urm"
wcdma_ss_imgc  = "ss_msc"
wcdma_ss_imgw  = "ss_msc"
wcdma_ss_mgw   = "ss_msc"
wcdma_ss_msc   = "ss_msc"
wcdma_ss_mtru  = "ss_mtru"
wcdma_ss_sgsnm = "ss_msc"
wcdma_ss_sgsnt = "ss_msc"
wcdma_ss_tan   = "ss_urm"
wcdma_ss_urm   = "ss_urm"
wcdma_tw_wglr  = "tw_vmss"

test_uv_xyz    = "uv_xyz"

