team_id = ["00001200", "00001300"]

log = "/home/sanxoo/codes/animp-reno/log"

[maria]
host = "192.168.105.36"
port = 3306
user = "animp"
password = "gn64T/+uzkPQ2IoqiOVegA=="
database = "animp"

[iris]
master = "192.168.105.36:5050"
user = "animp"
password = "gn64T/+uzkPQ2IoqiOVegA=="
database = "animp"

[ui_api]
auth_key = "gn64T/+uzkPQ2IoqiOVegA=="

